name: mlflow_orch

channels:
  - conda-forge
dependencies:
  - python=3.10.17
  - hydra-core=1.3.2
  - omegaconf=2.3.0
  - python-dotenv=1.1.0
  - pyyaml=6.0.2
  - pip=25.1.1
  - pip:
      - mlflow-skinny==2.22.0
      - wandb==0.19.11
