# config.yaml
# All pipeline configuration lives here. Override any parameter via Hydra CLI or MLflow hydra_options.
main:
  WANDB_PROJECT: opioid_mlops_project
  WANDB_ENTITY: idiazl  # Replace with your actual wandb entity/team
  steps: all            # e.g., "data_load,data_validation,train_model"
  hydra_options: ""     # Add this line for CLI/MLflow runtime overrides

data_source:
  raw_path: "./data/raw/opiod_raw_data.csv" # Relative to project root
  processed_path: "./data/processed/opiod_processed_data.csv"
  type: "csv"
  sheet_name: "Sheet1"       # Only used if type == 'excel'
  delimiter: ","             # Only used if type == 'csv'
  header: 0
  encoding: "utf-8"

logging:
  level: "INFO"
  log_file: "./logs/main.log"
  format: "%(asctime)s - %(levelname)s - %(name)s - %(message)s"
  datefmt: "%Y-%m-%d %H:%M:%S"

data_split:
  test_size: 0.2
  valid_size: 0.2
  random_state: 42

model:
  active: decision_tree
  decision_tree:
    save_path: models/decision_tree.pkl
    params:
      max_depth: 4
      random_state: 42
  logistic_regression:
    save_path: models/logistic_regression.pkl
    params:
      penalty: l2
      solver: lbfgs
      random_state: 42
      max_iter: 200
  random_forest:
    save_path: models/random_forest.pkl
    params:
      n_estimators: 100
      max_depth: 5
      random_state: 42

raw_features:  
  - "rx ds"
  - A
  - B
  - C
  - D
  - E
  - F
  - H
  - I
  - J
  - K
  - L
  - M
  - N
  - R
  - S
  - T
  - V

features:
  continuous:
    - rx_ds
    - risk_score
  categorical: []
  engineered:
    - risk_score
    - rx_ds_norm
    - rx_ds_bucket_Q1
    - rx_ds_bucket_Q2
    - rx_ds_bucket_Q3
    - rx_ds_bucket_Q4
    - A
    - B
    - C
    - D
    - E
    - F
    - H
    - I
    - J
    - K
    - L
    - M
    - N
    - R
    - S
    - T
    - V

icd10_chapter_flags:
  - A
  - B
  - C
  - D
  - E
  - F
  - H
  - I
  - J
  - K
  - L
  - M
  - N
  - R
  - S
  - T
  - V

target: OD

metrics:
  display:
    - Accuracy
    - F1 Score
    - ROC AUC
  report:
    - Accuracy
    - Precision (PPV)
    - Specificity
    - F1 Score
    - Negative Predictive Value (NPV)
    - ROC AUC
    - Confusion Matrix

preprocessing:
  rename_columns:
    "rx ds": rx_ds
  rx_ds:
    normalization: minmax
    bucketize: true
    n_buckets: 4
    bucket_labels: [Q1, Q2, Q3, Q4]
    one_hot_encode_buckets: true

artifacts:
  metrics_path: models/metrics.json
  preprocessing_pipeline: models/preprocessing_pipeline.pkl
  splits_dir: data/splits
  processed_dir: data/processed

data_validation:
  enabled: true
  action_on_error: "raise"
  report_path: "logs/validation_report.json"
  schema:
    columns:
      - name: "ID"
        dtype: "int"
        required: true
        min: 1
      - name: "OD"
        dtype: "int"
        required: false
        allowed_values: [0, 1]
      - name: "Low_inc"
        dtype: "int"
        required: true
        allowed_values: [0, 1]
      - name: "SURG"
        dtype: "int"
        required: true
        allowed_values: [0, 1]
      - name: "rx ds"
        dtype: "int"
        required: true
        min: 0
        max: 2000
      - name: "A"
        dtype: "int"
        required: true
        allowed_values: [0, 1]
      - name: "B"
        dtype: "int"
        required: true
        allowed_values: [0, 1]
      - name: "C"
        dtype: "int"
        required: true
        allowed_values: [0, 1]
      - name: "D"
        dtype: "int"
        required: true
        allowed_values: [0, 1]
      - name: "E"
        dtype: "int"
        required: true
        allowed_values: [0, 1]
      - name: "F"
        dtype: "int"
        required: true
        allowed_values: [0, 1]
      - name: "H"
        dtype: "int"
        required: true
        allowed_values: [0, 1]
      - name: "I"
        dtype: "int"
        required: true
        allowed_values: [0, 1]
      - name: "J"
        dtype: "int"
        required: true
        allowed_values: [0, 1]
      - name: "K"
        dtype: "int"
        required: true
        allowed_values: [0, 1]
      - name: "L"
        dtype: "int"
        required: true
        allowed_values: [0, 1]
      - name: "M"
        dtype: "int"
        required: true
        allowed_values: [0, 1]
      - name: "N"
        dtype: "int"
        required: true
        allowed_values: [0, 1]
      - name: "R"
        dtype: "int"
        required: true
        allowed_values: [0, 1]
      - name: "S"
        dtype: "int"
        required: true
        allowed_values: [0, 1]
      - name: "T"
        dtype: "int"
        required: true
        allowed_values: [0, 1]
      - name: "V"
        dtype: "int"
        required: true
        allowed_values: [0, 1]

data_load:
  data_stage: "raw"
  output_dir: "artifacts"
  log_artifacts: true
  log_summary_stats: true
  log_sample_artifacts: true
