name: data_load

channels:
  - conda-forge

dependencies:
  - python=3.10.17
  - pandas=2.2.3
  - hydra-core=1.3.2
  - omegaconf=2.3.0
  - python-dotenv=1.1.0
  - pyyaml=6.0.2
  - openpyxl=3.1.5
  - pip=25.1.1
  - pip:
      - wandb==0.19.11
